### ISSUE TITLE
Website not loading correctly

### ISSUE THREAD

**Issue by KevinFauth** [mdbootstrap/TW-Elements-React#162]
Visiting parts of the React Docs is giving a 50x's

![tw-elements-docs](https://github.com/mdbootstrap/TW-Elements-React/assets/2074492/dd211dcb-0fb3-4816-af24-8037edf4e1e1)

**Comment by iprzybysz** [comment]
Hi @KevinFauth, sorry for this incident. Now, everything should work correctly.

**Comment by KevinFauth** [comment]
Looks good @iprzybysz ! Thank you!
